services:
  - type: web
    name: candy-dash
    runtime: python
    region: virginia
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout 120 --workers 2 --preload
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
